name: pycequeau
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - gdal=3.11.0
  - pyproj
  - xarray
  - pytest
  - scipy
  - autopep8
  - matplotlib
  - ipykernel
  - geopandas
  - rasterstats
  - netcdf4
  - shapely >= 2.0
